REVIEW | Add Services page
Cornerstone-CICCC/web-1-final-project-term4 pull request #3
Opened 2024-11-16 17:50 UTC by ayakakojimaak

2024-11-16 17:53 UTC, ayakakojimaak commented on src/pages/services.html
> +    <header class="header">
I don't modify the header or footer.

2024-11-16 18:00 UTC, ayakakojimaak commented on src/scss/partials/_common.scss
> +
This CSS is also used for the About page.

2024-11-16 18:00 UTC, ayakakojimaak commented on src/scss/partials/_variables.scss
> +//TODO move to style.scss
I include this here to prevent any potential conflict.

2024-11-16 19:52 UTC, kazuki-0418 requested changes
I'd like you to modify part of `content-headline__subtitle`
sentences are different from Figma design

![image](https://github.com/user-attachments/assets/7910d0da-b2a8-4d07-bd8b-1a16f1597eb0)


## Figma design
![image](https://github.com/user-attachments/assets/9707144c-c7e3-4fc8-8a74-17aa3c0278bc)

2024-11-17 05:48 UTC, ayakakojimaak commented
@kazuki-0418 
Thank you for your comment!
I modified sentences🙏
[fix text](https://github.com/Cornerstone-CICCC/web-1-final-project-term4/pull/3/commits/899e587dba1bbb69ada3afcb33699ab025cd91af)

<img width="1440" alt="Screenshot 2024-11-16 at 9 46 08 PM" src="https://github.com/user-attachments/assets/0c6094d5-47b7-4797-a908-7beb459d2470">

2024-11-17 07:53 UTC, kazuki-0418 approved these changes
Thank you for completing the Service page!!👍

LGTM

2024-11-17 07:53 UTC, merged